name: Training
description: issues related to ONNX Runtime training
title: "[Training]: "
labels: ["training"]
assignees: "sophies927"
body:
  - type: markdown
    attributes:
      value: |
        If your request is a question/idea or otherwise not related to a bug/issue or feature request, please submit to [ONNX Runtime GitHub Discussions](https://github.com/microsoft/onnxruntime/discussions).
        Before submitting your request, please review past submissions to ensure that it is not a duplicate of a known issue.
  - type: textarea
    id: issue-descript
    attributes:
      label: Describe the issue
    validations:
      required: true
  - type: textarea
    id: urgency
    attributes:
      label: Urgency
      placeholder: Is your issue urgent? If important use cases are blocked, there is a regression in ONNX Runtime functionality, or you have a strict project deadline, please elaborate here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        # System information
        For each of the following items, provide the information listed to ensure that your request is addressed in a timely manner.
  - type: dropdown
    id: train-plat
    attributes:
      label: Platform
      options:
        - Linux
        - Windows
        - Mac
        - Other / Unknown
    validations:
      required: true
  - type: dropdown
    id: train-api
    attributes:
      label: API
      options:
        - PyTorch 1.8.1
        - PyTorch 1.9
        - C++
        - Other / Unknown
    validations:
      required: true
  - type: dropdown
    id: hardware-accel
    attributes:
      label: Hardware Acceleration
      options:
        - Default CPU
        - CUDA 10.2
        - CUDA 11.1
        - ROCm 4.2
        - ROCm 4.3.1
        - oneDNN
        - Other / Unknown
    validations:
      required: true
  - type: input
    id: ha-version
    attributes:
      label: Hardware Acceleration Version
      placeholder: ex. 2022.1
    validations:
      required: true
  - type: input
    id: vs-version
    attributes:
      label: Visual Studio Version (if applicable)
      placeholder: ex. 17.2.5
  - type: input
    id: comp-version
    attributes:
      label: GCC / Compiler Version (if installed from source)
      placeholder: ex. 4.8.3
  - type: textarea
    id: reproducibility
    attributes:
      label: To reproduce
      placeholder: Code to reproduce your issue (if necessary).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      placeholder: Provide any additional context necessary for your issue to be addressed (e.g., screenshots, GPU model & memory, etc.).
