name: Feature Request
description: requests for new ONNX Runtime features
body:
  - type: markdown
    attributes:
      value: |
        Before submitting your request, please review past submissions to ensure that it is not a duplicate of a known feature request.
  - type: textarea
    id: fr-descrip
    attributes:
      label: Describe the feature request
      placeholder: A clear and concise description of the feature you would like and why it should be added. Include a clear and concise description of any alternative solutions or features you've considered and provide any additional context necessary for your issue to be addressed (e.g., screenshots, GPU model & memory, etc.).
    validations:
      required: true
  - type: input
    id: ort-version
    attributes:
      label: ONNX Runtime Version or Commit ID
      placeholder: ex. 1.12.1
    validations:
      required: true
